# Exploratory Data Analysis
Understanding the dataset to explore how the data is present in the database and if there is a need of creating some aggregated tables that can help with:
* Vendor selection for profitability
* Product pricing optimization

In [2]:
import pandas as pd
import sqlite3

In [3]:
# creating database connection
conn = sqlite3.connect('inventory.db')

In [4]:
# checking tables present in the database
tables = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type = 'table'", conn)
tables

              name
0   vendor_invoice
1  purchase_prices
2            sales
3        purchases
4  begin_inventory
5    end_inventory

In [ ]:
for table in tables['name']:
    print('-'*50, f'{table}', '-'*50)
    print('count of records:', pd.read_sql(f"select count(*) as count from {table}", conn)['count'].values[0])
    display(pd.read_sql(f"select * from {table} limit 5", conn))

-------------------------------------------------- vendor_invoice --------------------------------------------------
count of records: 22172

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,None

-------------------------------------------------- purchase_prices --------------------------------------------------
count of records: 49044

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

-------------------------------------------------- sales --------------------------------------------------

In [5]:
purchases = pd.read_sql_query(
    "SELECT * FROM purchases WHERE VendorNumber = 4466 LIMIT 500",
    conn
)
purchases

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
1,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
2,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
3,38_GOULCREST_5215,38,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-07,2024-01-19,2024-02-26,9.41,6,56.46,1
4,59_CLAETHORPES_5215,59,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-05,2024-01-19,2024-02-26,9.41,6,56.46,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,55_DRY GULCH_3140,55,3140,TGI Fridays Orange Dream,1.75L,4466,AMERICAN VINTAGE BEVERAGE,9886,2024-04-21,2024-04-27,2024-05-09,2024-06-12,11.19,6,67.14,1
496,33_HORNSEY_5255,33,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,9886,2024-04-21,2024-04-28,2024-05-09,2024-06-12,9.35,6,56.10,1
497,79_BALLYMENA_5215,79,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,9999,2024-04-29,2024-05-05,2024-05-14,2024-06-26,9.41,6,56.46,1
498,67_EANVERNESS_3140,67,3140,TGI Fridays Orange Dream,1.75L,4466,AMERICAN VINTAGE BEVERAGE,9999,2024-04-29,2024-05-04,2024-05-14,2024-06-26,11.19,6,67.14,1
499,8_ALNERWICK_5215,8,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,9999,2024-04-29,2024-05-02,2024-05-14,2024-06-26,9.41,6,56.46,1

In [6]:
purchase_prices = pd.read_sql_query(
    "SELECT * FROM purchase_prices WHERE VendorNumber = 4466 LIMIT 500",
    conn
)
purchase_prices

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,5215,TGI Fridays Long Island Iced,12.99,1750mL,1750,1,9.41,4466,AMERICAN VINTAGE BEVERAGE
1,5255,TGI Fridays Ultimte Mudslide,12.99,1750mL,1750,1,9.35,4466,AMERICAN VINTAGE BEVERAGE
2,3140,TGI Fridays Orange Dream,14.99,1750mL,1750,1,11.19,4466,AMERICAN VINTAGE BEVERAGE
3,5215,TGI Fridays Long Island Iced,12.99,1750mL,1750,1,9.41,4466,AMERICAN VINTAGE BEVERAGE
4,5255,TGI Fridays Ultimte Mudslide,12.99,1750mL,1750,1,9.35,4466,AMERICAN VINTAGE BEVERAGE
5,3140,TGI Fridays Orange Dream,14.99,1750mL,1750,1,11.19,4466,AMERICAN VINTAGE BEVERAGE
6,5215,TGI Fridays Long Island Iced,12.99,1750mL,1750,1,9.41,4466,AMERICAN VINTAGE BEVERAGE
7,5255,TGI Fridays Ultimte Mudslide,12.99,1750mL,1750,1,9.35,4466,AMERICAN VINTAGE BEVERAGE
8,3140,TGI Fridays Orange Dream,14.99,1750mL,1750,1,11.19,4466,AMERICAN VINTAGE BEVERAGE
9,5215,TGI Fridays Long Island Iced,12.99,1750mL,1750,1,9.41,4466,AMERICAN VINTAGE BEVERAGE
10,5255,TGI Fridays Ultimte Mudslide,12.99,1750mL,1750,1,9.35,4466,AMERICAN VINTAGE BEVERAGE
11,3140,TGI Fridays Orange Dream,14.99,1750mL,1750,1,11.19,4466,AMERICAN VINTAGE BEVERAGE

In [7]:
vendor_invoice = pd.read_sql_query(
    "SELECT * FROM vendor_invoice WHERE VendorNumber = 4466 LIMIT 500",
    conn
)
vendor_invoice

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-19,8207,2023-12-27,2024-02-26,335,3142.33,16.97,None
2,4466,AMERICAN VINTAGE BEVERAGE,2024-01-18,8307,2024-01-03,2024-02-18,41,383.35,1.99,None
3,4466,AMERICAN VINTAGE BEVERAGE,2024-01-27,8469,2024-01-14,2024-03-11,72,673.20,3.30,None
4,4466,AMERICAN VINTAGE BEVERAGE,2024-02-04,8532,2024-01-19,2024-03-15,79,740.21,3.48,None
...,...,...,...,...,...,...,...,...,...,...
215,4466,AMERICAN VINTAGE BEVERAGE,2024-12-06,13134,2024-11-20,2025-01-18,305,3018.89,15.70,None
216,4466,AMERICAN VINTAGE BEVERAGE,2024-12-16,13254,2024-11-28,2025-01-13,262,2530.36,11.39,None
217,4466,AMERICAN VINTAGE BEVERAGE,2024-12-26,13432,2024-12-09,2025-01-27,231,2263.43,11.32,None
218,4466,AMERICAN VINTAGE BEVERAGE,2024-12-30,13483,2024-12-13,2025-02-11,221,2178.27,11.33,None
219,4466,AMERICAN VINTAGE BEVERAGE,2025-01-09,13627,2024-12-22,2025-02-05,413,3985.03,19.53,None

In [8]:
sales = pd.read_sql_query(
    "SELECT * FROM sales WHERE VendorNo = 4466 LIMIT 500",
    conn
)
sales

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-09,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
1,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-12,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
2,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-15,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
3,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-21,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
4,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-23,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,32_MOUNTMEND_5255,32,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-02-25,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
496,33_HORNSEY_5215,33,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-02-02,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
497,33_HORNSEY_5215,33,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-02-06,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
498,33_HORNSEY_5215,33,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-02-27,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
499,33_HORNSEY_5215,33,5215,TGI Fridays Long Island Iced,1.75L,12,155.88,12.99,2024-02-28,1750.0,1,22.05,4466,AMERICAN VINTAGE BEVERAGE

In [9]:
# purchases_summary = pd.read_sql_query("""
#     SELECT Brand, PurchasePrice,
#            SUM(Quantity) as total_qty,
#            SUM(Dollars) as total_dollars
#     FROM purchases
#     WHERE VendorNumber = 4466
#     GROUP BY Brand, PurchasePrice
# """, conn)
# purchases_summary.head()

purchases.groupby(['Brand', 'PurchasePrice'])[['Quantity', 'Dollars']].sum()

                     Quantity   Dollars
Brand PurchasePrice
3140  11.19               458   5125.02
5215  9.41               1368  12872.88
5255  9.35               1521  14221.35

In [10]:
# sales_summary = pd.read_sql_query("""
#     SELECT Brand,
#            SUM(SalesDollars) as total_sales,
#            SUM(SalesPrice) as total_price,
#            SUM(SalesQuantity) as total_qty
#     FROM sales
#     WHERE VendorNo = 4466
#     GROUP BY Brand
# """, conn)

sales.groupby('Brand')[['SalesDollars','SalesPrice', 'SalesQuantity']].sum()

       SalesDollars  SalesPrice  SalesQuantity
Brand
5215        4598.46     2831.82            354
5255        4845.27     3663.18            373

## Insight
* The purchases table contains actual purchases data, including the purchases date, product purchases by vendor, the ammount paid, and the quantity purchased.
* The purchase price column in derived from the purchase_price table which provides product wise actual and purchase price. The combination of vendor and brand is unique in this table.
* The vendor_invoice table aggregates data from the purchases table, summarizing quantity and dollar amounts, along with and additional column for freight. This table maintains uniqueness based on vendor and PO number.
* The sales table captures actual sales transactions, detailing the brand purchased by vendors, the quantity sold, the selling price and the revenue earned
---
As the data we need for analysis is distributed in different tables, we need to create a summary table containing :
* Purchased transactions made by vendor
* Sales transaction data
* Freight costs for each vendor
* Actual product price from vendors

In [11]:
# Freight cost
# first check the vendor_invoice columns
vendor_invoice.columns

Index(['VendorNumber', 'VendorName', 'InvoiceDate', 'PONumber', 'PODate',
       'PayDate', 'Quantity', 'Dollars', 'Freight', 'Approval'],
      dtype='str')

In [12]:
fright_summary = pd.read_sql_query(
    """
    select VendorNumber, sum(Freight) as FrightCost
    from vendor_invoice
    group by VendorNumber
    """,
    conn
)
fright_summary

     VendorNumber  FrightCost
0               2      108.32
1              54        1.92
2              60     1470.08
3             105      249.56
4             200       24.76
..            ...         ...
121         98450     3424.08
122         99166      520.36
123        172662      713.36
124        173357      810.00
125        201359        0.36

[126 rows x 2 columns]

In [13]:
# purchases prices
# first check the columns
purchases.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'VendorNumber',
       'VendorName', 'PONumber', 'PODate', 'ReceivingDate', 'InvoiceDate',
       'PayDate', 'PurchasePrice', 'Quantity', 'Dollars', 'Classification'],
      dtype='str')

In [14]:
purchase_prices.columns

Index(['Brand', 'Description', 'Price', 'Size', 'Volume', 'Classification',
       'PurchasePrice', 'VendorNumber', 'VendorName'],
      dtype='str')

In [15]:
pd.read_sql_query(
    """
    select 
    p.VendorNumber,
    p.VendorName,
    p.Brand,
    p.PurchasePrice,
    pp.Volume,
    pp.Price as ActualPrice,
    sum(p.Quantity) as TotalPurchaseQuantity,
    sum(p.Dollars) as TotalPurchaseDollars
    from purchases p
    join purchase_prices pp
    on p.Brand = pp.Brand
    where p.PurchasePrice > 0
    group by p.VendorNumber, p.VendorName, p.Brand
    order by TotalPurchaseDollars
    """,
    conn
)

,VendorNumber,VendorName,Brand,PurchasePrice,Volume,ActualPrice,TotalPurchaseQuantity,TotalPurchaseDollars
0,7245,PROXIMO SPIRITS INC.,3065,0.71,50,0.99,8,5.68
1,3960,DIAGEO NORTH AMERICA INC,6127,1.47,200,1.99,8,11.76
2,3924,HEAVEN HILL DISTILLERIES,9123,0.74,50,0.99,16,11.84
3,8004,SAZERAC CO INC,5683,0.39,50,0.49,48,18.72
4,9815,WINE GROUP INC,8527,1.32,750,4.99,16,21.12
...,...,...,...,...,...,...,...,...
10687,3960,DIAGEO NORTH AMERICA INC,3545,21.89,1750,29.99,1131620,24771161.80
10688,3960,DIAGEO NORTH AMERICA INC,4261,16.17,1750,22.99,1660844,26855847.48
10689,17035,PERNOD RICARD USA,8068,18.24,1750,24.99,1515012,27633818.88
10690,4425,MARTIGNETTI COMPANIES,3405,23.19,1750,28.99,1332792,30907446.48
10691,1128,BROWN-FORMAN CORP,1233,26.27,1750,36.99,1181780,31045360.60

In [16]:
# sales table
# check column
sales.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'SalesQuantity',
       'SalesDollars', 'SalesPrice', 'SalesDate', 'Volume', 'Classification',
       'ExciseTax', 'VendorNo', 'VendorName'],
      dtype='str')

In [17]:
pd.read_sql_query(
    """
    select
    VendorNo,
    Brand,
    sum(SalesDollars) as TotalSalesDollars,
    sum(SalesPrice) as TotalSalesPrice,
    sum(SalesQuantity) as TotalSalesQuantity,
    sum(ExciseTax) as TotalExciseTax
    from sales
    group by VendorNo, Brand
    """, 
    conn
)

,VendorNo,Brand,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax
0,2,90085,1923.48,850.77,52,5.78
1,2,90609,1799.28,1349.46,72,1.56
2,60,771,1573.95,1139.24,105,82.70
3,60,3979,154387.34,96668.27,9066,16660.85
4,105,2529,899.70,149.95,30,23.60
...,...,...,...,...,...,...
11267,173357,2804,12597.20,6388.58,280,220.66
11268,173357,3666,22790.88,11920.23,912,357.73
11269,173357,3848,371.88,185.94,12,9.42
11270,173357,3909,63624.54,36685.32,2546,2006.38
11271,201359,90609,3298.68,2923.83,132,2.79

In [20]:
import time 
start = time.time()
vendor_sales_summary = pd.read_sql_query("""
    
    SELECT
        pp.VendorNumber,
        pp.Brand,
        pp.Price AS ActualPrice,
        pp.PurchasePrice,

        s.TotalSalesQuantity,
        s.TotalSalesDollars,
        s.TotalSalesPrice,
        s.TotalExciseTax,

        vi.TotalPurchaseQuantity,
        vi.TotalPurchaseDollars,
        vi.TotalFreightCost

    FROM purchase_prices pp

    LEFT JOIN (
        SELECT
            VendorNo,
            Brand,
            SUM(SalesQuantity) AS TotalSalesQuantity,
            SUM(SalesDollars) AS TotalSalesDollars,
            SUM(SalesPrice) AS TotalSalesPrice,
            SUM(ExciseTax) AS TotalExciseTax
        FROM sales
        GROUP BY VendorNo, Brand
    ) s
    ON pp.VendorNumber = s.VendorNo AND pp.Brand = s.Brand

    LEFT JOIN (
        SELECT
            VendorNumber,
            SUM(Quantity) AS TotalPurchaseQuantity,
            SUM(Dollars) AS TotalPurchaseDollars,
            SUM(Freight) AS TotalFreightCost
        FROM vendor_invoice
        GROUP BY VendorNumber
    ) vi
    ON pp.VendorNumber = vi.VendorNumber

""", conn)
end = time.time()
print('Time taken to execute the query:', end - start, 'seconds')

Time taken to execute the query: 98.27315592765808 seconds

In [21]:
vendor_sales_summary

,VendorNumber,Brand,ActualPrice,PurchasePrice,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,TotalPurchaseQuantity,TotalPurchaseDollars,TotalFreightCost
0,8320,58,12.99,9.28,8801.0,111286.99,72263.89,6934.42,276508.0,2.499919e+06,12607.68
1,1128,62,36.99,28.67,8163.0,312939.37,235775.54,6434.21,4024488.0,5.411773e+07,274406.72
2,1128,63,38.99,30.46,7175.0,289683.25,228335.47,5657.46,4024488.0,5.411773e+07,274406.72
3,9165,72,34.99,26.11,1247.0,45942.53,32801.06,983.31,4310108.0,5.284246e+07,272218.80
4,7245,75,14.99,10.94,61.0,914.39,389.74,48.02,2728168.0,3.035212e+07,155979.12
...,...,...,...,...,...,...,...,...,...,...,...
49039,90024,44917,24.99,16.55,2.0,49.98,49.98,0.22,237712.0,2.195421e+06,11210.56
49040,4425,44944,22.99,14.93,2266.0,52095.34,23495.78,252.76,10561644.0,1.114468e+08,579716.96
49041,10754,45016,93.99,61.43,4.0,375.96,375.96,0.44,2212464.0,2.266201e+07,114882.08
49042,9744,46011,12.99,8.90,8.0,103.92,51.96,1.80,283728.0,3.037797e+06,15999.72
49043,10754,46964,35.99,24.32,8.0,287.92,143.96,0.88,2212464.0,2.266201e+07,114882.08

This query generates a vendor wise sales and purchase summary, which is valuable for:  
**Performance Optimization:**  
* The query involves heavy joins and aggregations on large datasets like sales and purchase.
* Storing the pre-aggregation results avoids repated expensive computation.
* Helps in analyzing sales, purchases and pricing for different vendors and brands.
* Future Benefits of Storing this data for faster dashboarding and reporting.
* Instead of running expensive queries each time, dashboards can featch data quickly from vendor_sales_summary